services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "status"]
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  activity-service:
    build: ./services/activity
    volumes:
      - ./services/activity:/app
      - ./services/activity/data:/app/data

  bid-service:
    build: ./services/bid
    env_file:
      - .env
    volumes:
      - ./services/bid:/app
      - ./services/bid/data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  listing-service:
    build: ./services/listing
    env_file:
      - .env
    volumes:
      - ./services/listing:/app
      - ./services/listing/data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy

  auth-service:
    build: ./services/auth
    env_file:
      - .env
    volumes:
      - ./services/auth:/app
      - ./services/auth/data:/app/data

  api-gateway:
    build: ./services/gateway
    ports:
      - "8000:8000"
    volumes:
      - ./services/gateway:/app
    env_file:
      - .env
    depends_on:
      - auth-service
      - activity-service
      - bid-service
      - listing-service