"""change id to int auto increment

Revision ID: 8d468a4b826c
Revises: 8b9ee57c58af
Create Date: 2026-06-06 21:02:45.664525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d468a4b826c'
down_revision: Union[str, None] = '8b9ee57c58af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')

    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id TYPE integer USING id::integer")
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN user_id TYPE integer USING user_id::integer")

    op.execute("ALTER TABLE users ALTER COLUMN id TYPE integer USING id::integer")
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

    op.create_foreign_key(
        'refresh_tokens_user_id_fkey',
        'refresh_tokens',
        'users',
        ['user_id'],
        ['id'],
    )


def downgrade() -> None:
    op.drop_constraint('refresh_tokens_user_id_fkey', 'refresh_tokens', type_='foreignkey')

    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE users ALTER COLUMN id TYPE varchar USING id::varchar")

    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN id TYPE varchar USING id::varchar")
    op.execute("ALTER TABLE refresh_tokens ALTER COLUMN user_id TYPE varchar USING user_id::varchar")

    op.create_foreign_key(
        'refresh_tokens_user_id_fkey',
        'refresh_tokens',
        'users',
        ['user_id'],
        ['id'],
    )
