"""db init

Revision ID: a77c6424d710
Revises: 
Create Date: 2026-06-08 17:52:36.487367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a77c6424d710'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('bidder_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bids_auction_id'), ['auction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bids_bidder_id'), ['bidder_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bids_bidder_id'))
        batch_op.drop_index(batch_op.f('ix_bids_auction_id'))

    op.drop_table('bids')
    # ### end Alembic commands ###
